### ISSUE TITLE
How to uninstall on DSM 7.0?

### ISSUE THREAD

**Issue by yduke** [darknebular/Wrapper_VideoStation#1]
Thank you!

I installed the wapper on DSM 7.0-4189 but it seems something was wrong, the previously working transcoding job does not work anymore, I want to uninstall the wapper.
Will you please update the instructions for Remove / Uninstall on DSM 7.0?

Thank you.

**Comment by Letmeload** [comment]
Go to packagemanager
Delete ffmpeg
Delete and reinstall Videostation with Advanced Media Extensions (keep the video database).
