### ISSUE TITLE
Are there something wrong in installer.sh 635:638

### ISSUE THREAD

**Issue by DoffeBupt** [darknebular/Wrapper_VideoStation#12]
function check_versions() {
# NO SE TRADUCE

if [[ "$dsm_version" == 7.0* ]]; then
cp_bin_path=/var/packages/CodecPack/target/bin
  injector="0-12.2.4"
fi

if [[ "$dsm_version" == 7.1* ]]; then
cp_bin_path=/var/packages/CodecPack/target/pack/bin
  injector="1-12.3.5"
else
error "Your DSM Version $dsm_version is NOT SUPPORTED using this Installer. Please use the MANUAL Procedure."
error "Your DSM Version $dsm_version is NOT SUPPORTED using this Installer. Please use the MANUAL Procedure." >> $logfile
 exit 1
fi
}

i mean, if i am of the dsm version of 7.0.X, then i must raise an error. the second if should be something like 'elif' in python?

**Comment by darknebular** [comment]
Hello, 

no. It's OK. As if you have 7.1.X you will match in the second conditional.
if [[ "$dsm_version" == 7.1* ]]; then

If you have 7.0.X you will match in the first conditional.
**if [[ "$dsm_version" == 7.0* ]]; then**
When you install, Can you tell what injector will put to you?

Best regards.

**Comment by DoffeBupt** [comment]
Yep, my dsm version is 7.0.1 and it told me that 7.0.1 is not supported. After I commented the second conditional, the installation’s successfully achieved.


Best regards!
--------------原始邮件--------------
发件人："darknebular ***@***.***&gt;;
发送时间：2022年12月4日(星期天) 凌晨2:11
收件人："darknebular/Wrapper_VideoStation" ***@***.***&gt;;
抄送："侯朝晖 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [darknebular/Wrapper_VideoStation] Are there something wrong in installer.sh 635:638 (Issue #12)
-----------------------------------

 

 
Hello,
 
no. It's OK. As if you have 7.1.X you will match in the second conditional.
 if [[ "$dsm_version" == 7.1* ]]; then
 
If you have 7.0.X you will match in the first conditional.
 if [[ "$dsm_version" == 7.0 ]]; then*
 When you install, Can you tell what injector will put to you?
 
Best regards.

**Comment by darknebular** [comment]
Can you try with this?
`bash -c "$(curl "https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/testing.sh")"

`

**Comment by darknebular** [comment]
Inn 7.0 the correct path in the variable cp_bin_path is: 
cp_bin_path=**/var/packages/CodecPack/target/bin**

**Comment by darknebular** [comment]
I have 7.1.1 and It's working with 7.1* into the conditional.

It must be working fine with 7.0.1 too...

**Comment by DoffeBupt** [comment]
But will it be possible that it reach into the both conditional when the version is 7.0.1? And then it will echo “Your dam version is 7.0.1 is not supported using this installer”, which it happened to me emmm…
--------------原始邮件--------------
发件人："darknebular ***@***.***&gt;;
发送时间：2022年12月4日(星期天) 凌晨2:24
收件人："darknebular/Wrapper_VideoStation" ***@***.***&gt;;
抄送："侯朝晖 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [darknebular/Wrapper_VideoStation] Are there something wrong in installer.sh 635:638 (Issue #12)
-----------------------------------

 

 
I have 7.1.1 and It's working with 7.1* into the conditional.
 
It must be working fine with 7.0.1 too...

**Comment by DoffeBupt** [comment]
I successfully installed your patch when I commented the second conditional, and emmm, here’s 2:19 am in my location and I’m going to sleep lol, and I’ll try your script some hours later?
--------------原始邮件--------------
发件人："darknebular ***@***.***&gt;;
发送时间：2022年12月4日(星期天) 凌晨2:19
收件人："darknebular/Wrapper_VideoStation" ***@***.***&gt;;
抄送："侯朝晖 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [darknebular/Wrapper_VideoStation] Are there something wrong in installer.sh 635:638 (Issue #12)
-----------------------------------

 

 
Can you try with this?
 `bash -c "$(curl "https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/testing.sh")"
 
`

**Comment by darknebular** [comment]
Fixed this bug in: **SCPT_2.8**

Thanks, best regards.
