### ISSUE TITLE
At least you need 3 package/s to Install, please Install the dependencies and RE-RUN the Installer again.

### ISSUE THREAD

**Issue by Paketa2** [darknebular/Wrapper_VideoStation#13]
Each of these packages are installed, but can't complete the install process.

\u001b[32m[2023-01-28 22:40:39] \u001b[31mERROR: \u001b[31mMISSING VideoStation Package.
\u001b[32m[2023-01-28 22:40:39] \u001b[31mERROR: \u001b[31mMISSING ffmpeg Package.
\u001b[32m[2023-01-28 22:40:39] \u001b[31mERROR: \u001b[31mMISSING CodecPack Package.
At least you need 3 package/s to Install, please Install the dependencies and RE-RUN the Installer again.

**Comment by darknebular** [comment]
Hello, can you do these commands?

`cd /var/packages/`
`ls -la`

Best regards.

**Comment by Paketa2** [comment]
total 144
drwxr-xr-x 36 root root 4096 Feb  2 22:04 .
drwxr-xr-x 15 root root 4096 Feb  4 07:01 ..
drwxr-xr-x  5 root root 4096 Feb  4 07:01 ActiveBackup-GSuite
drwxr-xr-x  4 root root 4096 Feb  4 07:01 ActiveInsight
drwxr-xr-x  5 root root 4096 Feb  4 07:01 AudioStation
drwxr-xr-x  5 root root 4096 Feb  4 07:02 Calendar
drwxr-xr-x  5 root root 4096 Feb  4 07:01 CloudSync
drwxr-xr-x  4 root root 4096 Feb  4 07:01 CodecPack
drwxr-xr-x  5 root root 4096 Feb  4 07:01 DhcpServer
drwxr-xr-x  5 root root 4096 Feb  4 07:01 Docker
drwxr-xr-x  5 root root 4096 Feb  4 07:01 DownloadStation
drwxr-xr-x  4 root root 4096 Feb  4 07:01 exFAT-Free
drwxr-xr-x  5 root root 4096 Feb  4 07:01 ffmpeg
drwxr-xr-x  4 root root 4096 Feb  4 07:01 FileStation
drwxr-xr-x  4 root root 4096 Feb  4 07:01 HybridShare
drwxr-xr-x  4 root root 4096 Feb  4 07:01 MailServer
drwxr-xr-x  4 root root 4096 Feb  4 07:02 MailStation
drwxr-xr-x  4 root root 4096 Feb  4 07:01 MediaServer
drwxr-xr-x  4 root root 4096 Feb  4 07:01 Node.js_v12
drwxr-xr-x  4 root root 4096 Feb  4 07:01 Node.js_v18
drwxr-xr-x  4 root root 4096 Feb  4 07:01 OAuthService
drwxr-xr-x  4 root root 4096 Feb  4 07:01 Perl
drwxr-xr-x  4 root root 4096 Feb  4 07:01 PHP7.0
drwxr-xr-x  4 root root 4096 Feb  4 07:01 PHP7.3
drwxr-xr-x  4 root root 4096 Feb  4 07:01 PHP7.4
drwxr-xr-x  4 root root 4096 Feb  4 07:01 Python2
drwxr-xr-x  5 root root 4096 Feb  4 07:01 ScsiTarget
drwxr-xr-x  4 root root 4096 Feb  4 07:01 SecureSignIn
drwxr-xr-x  4 root root 4096 Feb  4 07:01 SMBService
drwxr-xr-x  4 root root 4096 Feb  4 07:01 SynoFinder
drwxr-xr-x  5 root root 4096 Feb  4 07:01 SynologyApplicationService
drwxr-xr-x  5 root root 4096 Feb  4 07:02 SynologyDrive
drwxr-xr-x  5 root root 4096 Feb  4 07:01 SynologyPhotos
drwxr-xr-x  4 root root 4096 Feb  4 07:01 UniversalViewer
drwxr-xr-x  6 root root 4096 Feb  4 07:01 VideoStation
drwxr-xr-x  5 root root 4096 Feb  4 07:01 VPNCenter

**Comment by darknebular** [comment]
I see there that until yesterday at 07:01 you did not have those folders installed.

Have you tried now to try to install the script again?

Best regards.

**Comment by Paketa2** [comment]
Hey , I just restarted the installation from a different computer. It's now working. Thank you

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 5, 2023 at 11:51, ***@***.***> wrote:   


I see there that until yesterday at 07:01 you did not have those folders installed.

Have you tried now to try to install the script again?

Best regards.

**Comment by darknebular** [comment]
.
