### ISSUE TITLE
Infinite loading in VS when trying to read DTS, EAC3 video 

### ISSUE THREAD

**Issue by sebastienmure** [darknebular/Wrapper_VideoStation#14]
Hi,

It seems like i can't make the wrapper work. Every video file with DTS or EAC3 that i'm trying to read from the webbrowser video station result in an infinite loading :
![Capture d’écran du 2023-02-17 09-08-25](https://user-images.githubusercontent.com/9354959/219588257-6ad35202-40c7-432c-8e12-a0e59997192a.png)

For info :
Model : DS218
DSM : DSM 7.1.1-42962 Update 4
ffmpeg: 4.4.3-47
Videostation: 3.0.5-2503
AME: 3.0.1-2004

Thanks !

**Comment by darknebular** [comment]
Just tested now in a DS218 with the same DSM version and It's working fine.

Have you had other wrapper installed?

After installing the system's updates, have you reinstalled the wrapper?

**Comment by sebastienmure** [comment]
I had the Alex Presso's VideoStation-FFMPEG-Patcher, but yesterday when i got the DSM update, i found out your wrapper and decide to give it  a try. 

So if i'm not wrong, i believe the DSM update erase the installation of the previous patcher i used (not sure about that and it don't seems to be a uninstall procedure on his github), and i installed your wrapper after i got the DSM update.

**Comment by sebastienmure** [comment]
I just found that i got and 1080p h264 video file with DTS audio that work fine. The problem of infinite loading seems to be with 4k hevc DTS/EAC3. Maybe it's just that it's too much too handle for my DS218
