### ISSUE TITLE
Installer not compatible with DSM 7.2

### ISSUE THREAD

**Issue by alexandermayzel** [darknebular/Wrapper_VideoStation#16]
There is DSM 7.2 Beta available. The installer does not support it yet and fails to install.
Installed version is 7.2-64216

[2023-04-24 19:06:17] ERROR: Your DSM Version 7.2 is NOT SUPPORTED using this Installer. Please use the MANUAL Procedure.

https://prerelease.synology.com/en-global/download/dsm72_beta?builtin_name=synology_geminilake_220%2B

**Comment by dsfans** [comment]
Ok, I know. It Will be compatible as soon as possible.

Regards.

**Comment by sunnyxiong2020** [comment]
I just added rows as below and it seems to work fine
if [[ "$dsm_version" == 7.0* ]]; then
cp_bin_path=/var/packages/CodecPack/target/bin
  injector="0-12.2.5"
elif [[ "$dsm_version" == 7.1* ]]; then
cp_bin_path=/var/packages/CodecPack/target/pack/bin
  injector="1-12.3.6"
elif [[ "$dsm_version" == 7.2* ]]; then
cp_bin_path=/var/packages/CodecPack/target/pack/bin
  injector="1-12.3.6"

**Comment by darknebular** [comment]
@sunnyxiong2020 Could you send me a feedback of my Wrapper in DSM 7.2? It's working fine, you had needed to change something more?


Thanks in advance and best regards.

**Comment by darknebular** [comment]
It looks like that all is working fine with DSM 7.2.

I did a new version, It's a minor change and the version is **SCPT 2.9.1.**

I will close this ticket, thanks for all guys.

Best regards.

**Comment by sunnyxiong2020** [comment]
> @sunnyxiong2020 Could you send me a feedback of my Wrapper in DSM 7.2? It's working fine, you had needed to change something more?
> 
> Thanks in advance and best regards.

Works well so far! I mainly use the apps on the iPhone, no issue found.
