### ISSUE TITLE
"MODE = PIPE V_ORIG-A_WRAP" fails due to existing file

### ISSUE THREAD

**Issue by PetroLogic** [darknebular/Wrapper_VideoStation#2]
Thank you for your work on this wrapper and solution.

The "-f" option was missing from PARAM2 in the V_ORIG-A_Wrap section of the script starting at line 300 in the ffmpeg33 wrapper.  This caused the conversion to fail because the output file already existed from the earlier MODE = ORIG conversion attempt

My solution was to add args2vs+=("$1") after line 249 in the else section of the *) case.

This change added the "-f" and fixed my specific problem where the: 
VCODEC   = h264 (High) and the ACODEC   = eac3

No other testing was done....

**Comment by darknebular** [comment]
Thanks!!

But the wrapper ffmpeg33 is abandoned, now is ffmpeg41

**Comment by darknebular** [comment]
I added this line en ffmpeg33, thanks guy!!!

**Comment by darknebular** [comment]
Issue Closed
