### ISSUE TITLE
Video HEVC + AAC audio not working

### ISSUE THREAD

**Issue by Natzunur** [darknebular/Wrapper_VideoStation#22]
Hello,

I have installed your wrapper on my DS118, but my video is not working in Video Station (browser) 

HEVC + AAC => KO (echec de la lecture de la vidéo parce que le format de fichier de la piste audio actuellement sélectionnée n'est pas pris en charge)
HEVC + E-AC3 => KO (infinite loop)

**Comment by darknebular** [comment]
Your system hasn't got the performance for do 2 audio's streams (one of them with 5.1).
Do you tried with the Simplest one?

I recommend this wrapper in your case.

If you want still use the Advanced, in your case you must limit a one audio's stream this will help the requeriments to your CPU.
In order to do this, you must to enter into "The Configurator Tool" (Opción C in Main Menu) and then option G and then H.
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/b9b7159d-886b-4861-8f09-bdd520d0ee62)

![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/e4fee9cf-08dd-44dd-83fa-b78ab872f60d)


Best Regards.

**Comment by Natzunur** [comment]
Hi
Thanks for your message, I have installed the simplest but still the same

**Comment by darknebular** [comment]
Please could you try with the new version SCPT_3.2?
I did improvements in DLNA processing.

Thanks in advance.

**Comment by darknebular** [comment]
> Hi Thanks for your message, I have installed the simplest but still the same

**Please, could you send me the result of this command?**

`tail -n 200 -f /tmp/wrapper_ffmpeg.log`


Best regards.

**Comment by Natzunur** [comment]
root@synojb:~# tail -n 200 -f /tmp/wrapper_ffmpeg.log
tail: cannot open '/tmp/wrapper_ffmpeg.log' for reading: No such file or directory
tail: no files remaining

However : FFmpeg 4 + Advanced media extension are there..

**Comment by Natzunur** [comment]
It seems to be synology dependant de AAC support ? https://kb.synology.com/fr-fr/DSM/tutorial/Why_cant_I_play_AAC_encoded_files

The AAC support is gone seens 2022

**Comment by darknebular** [comment]
Don't worry about the support of AAC. My Wrapper will have always AAC codecs in its transcoding.
If you don't have wrapper_ffmpeg.log file logging, It's because you really don't have 100% installed my Wrapper.
Please, Could you try to re-install again?

Regards.

**Comment by Natzunur** [comment]
Did a new install , but still the same error message
![Capture d’écran 2023-05-14 194901](https://github.com/darknebular/Wrapper_VideoStation/assets/133401347/8933828b-4e4a-4ae1-9de4-0e4899ddf77b)
![Capture d’écran 2023-05-14 195127](https://github.com/darknebular/Wrapper_VideoStation/assets/133401347/f98d18ee-fb53-406f-9724-8cef4a50c36f)

**Comment by Natzunur** [comment]
What I did : 
- Install ffmpeg 4 + AME
- Patch Alex' Presso
- Unpatch Alex' Presso
- Patch Darknebular
- Unpatch Darknebular
- Patch Benjamain Poncet
- Remove ffmpeg 4 + AME
- Install ffmpeg 4 + AME
- Patch Darknebular (simplest)

Here we are
How can I check if VideoStation use ffmpeg 4 or another wrapper ?

**Big thanks for your time**

**Comment by darknebular** [comment]
First:
1) The Benjamin's wrapper was deprecated, you don't must use nowdays. In DSM 7.X is not necessary to change any binary in VideoStation Folder, only in AME or CodecPack path and only the ffmpeg41, the others binaries aren't using for playing movies.

2) The Alex's one changes ALL binaries in AME using a permanent link to a the binary changed in VideoStation.
**If you don't remove VideoStation, then the changes of others wrappers are still there. Please, uninstall the Video Station and re-install it again, then re-install again my simplest wrapper. The catalog of your movies doesn't lost.**

Please, you must to understand that in your model you only be able to play the movies with AC3, DTS, EAC3... not transcoding them. The wrapper with less requeriments is the Simplest one.



Regards.

**Comment by Natzunur** [comment]
I'dont have the hardware acceleration option (it's normal apparently)
![Capture d’écran 2023-05-15 195242](https://github.com/darknebular/Wrapper_VideoStation/assets/133401347/9d53c9df-6328-4d23-a67a-ca66de72f323)

**Comment by darknebular** [comment]
Please could you send me the result of this command?

`ls -la /var/packages/CodecPack/target/pack/bin/`

Regards.

**Comment by Natzunur** [comment]
```
drwxr-xr-x 2 root root   4096 May 15 14:41 .
drwxr-xr-x 6 root root   4096 May 15 14:29 ..
lrwxrwxrwx 1 root root     48 May 15 14:41 ffmpeg27 -> /var/packages/CodecPack/target/pack/bin/ffmpeg41
-rwxr-xr-x 1 root root 226024 Mar  3  2022 ffmpeg27.orig
-rwxr-xr-x 1 root root 246776 Mar  3  2022 ffmpeg33-for-surveillance
-rwxr-xr-x 1 root root   1929 May 15 14:41 ffmpeg41
-rwxr-xr-x 1 root root 259008 Mar  3  2022 ffmpeg41.orig
-rwxr-xr-x 1 root root  44168 Mar  3  2022 gst-inspect-1.0
-rwxr-xr-x 1 root root  35688 Mar  3  2022 gst-launch-1.0
-rwxr-xr-x 1 root root  10168 Mar  3  2022 gst-plugin-scanner

```

Thanks

**Comment by darknebular** [comment]
OK, I just tested in this device:
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/ef33adbe-d5bd-424e-a8d3-ce07a2917070)

It's very similar than your in performance. When I try to play HEVC in this system, the system doesn't touch my Wrapper, and I have a error saying: " You can't play it in your PC". Then, It's not related to my Wrapper, It's related to the CPU performance and hardware config in this system.
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/2587358b-bf40-4f57-8bd5-c1b761521510)
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/50e58839-81dd-4f7b-80cf-a2e249fb6d99)


When I play a .mkv with 264 codec and DTS, EAC3 It's working fine, and in this case, the system is using my Wrapper correctly.

![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/986e39a9-7b16-4b5d-9d66-26851a57578b)
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/5641b62a-231b-4a08-aa6d-417fefbf3658)


Then in your case, your problem with HEVC videos It's not related with my Wrapper.


Best regards.

**Comment by Natzunur** [comment]
It's not the video format that's the problem, it's the audio like in the first message.

![Capture d’écran 2023-05-18 134223](https://github.com/darknebular/Wrapper_VideoStation/assets/133401347/d44b63d0-4a79-41cb-9787-791833f3936b)

But thanks anyway for your time !

**Comment by darknebular** [comment]
You can check if my Wrapper is being used by looking at the logs.
Try a DTS or EAC3 movie using the h264 video codec and you will see that it does show up in the logs.
Your system when it is an HEVC video does not use my Wrapper.

Regards.

**Comment by darknebular** [comment]
I know that It isn't related to my Wrapper but I would like to help you a solution.

Regards.

**Comment by darknebular** [comment]
Yeah!! It's a Video Station related.

I think that you would fix it loading the .libs of GStreamer into the VideoStation/lib/ folder. I am studing this.

**Comment by darknebular** [comment]
As you can see there, not exists:
 type-name=GstOMXH265Dec

Due to This, you can decode hevc or h265 videos.

I think if you load the library for decoding 265 videos, you Will be able to play It.

I am a looking for the BEST way in order to do It.

**Comment by darknebular** [comment]
Sorry in your DSM must be here the other file:
Please send me This command:
`cat  var/packages/CodecPack/target/pack/etc/gstomx.conf`

**Comment by Natzunur** [comment]
Thanks a lot darknebular !

> adminjb@synojb:/$  cat  var/packages/CodecPack/target/pack/etc/gstomx.conf
> [omxmpeg2videodec]
> type-name=GstOMXMPEG2VideoDec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/mpeg,mpegversion=(int)[1, 2],systemstream=(boolean)false
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxmpeg4videodec]
> type-name=GstOMXMPEG4VideoDec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/mpeg,mpegversion=(int) 4, systemstream=(boolean)false;video/x-divx,divxversion=(int)[4,5]
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxh264dec]
> type-name=GstOMXH264Dec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-h264,alignment = (string) au,stream-format= (string) { avc }
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> 
> [omxvp9dec]
> type-name=GstOMXVP9Dec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec.vp9
> rank=50
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-vp9
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> 
> [omxvp8dec]
> type-name=GstOMXVP8Dec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-vp8
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxwmvdec]
> type-name=GstOMXWMVDec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-wmv, wmvversion=(int) 3, format=(string) { WMV3 WVC1 }
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxmjpegdec]
> type-name=GstOMXMJPEGDec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=image/jpeg
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxh263dec]
> type-name=GstOMXH263Dec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-h263,variant=(string)itu
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxh264enc]
> type-name=GstOMXH264Enc
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.enc
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-raw,format=(string) { NV12 },width=(int)[16, 4096],height=(int)[16, 4096],framerate=(fraction)[ 0/1, 2147483647/1 ]
> src-template-caps=video/x-h264,stream-format=(string){ avc }, alignment=(string){ au }, width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ], profile=(string){ high, main, baseline }
> hacks=no-disable-outport
> 
> [omxavsdec]
> type-name=GstOMXAVSDec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-cavs
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxh265dec]
> type-name=GstOMXH265Dec
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.video.dec
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-h265
> src-template-caps=video/x-raw,format = (string) { NV12 },width=(int)[ 16, 4096 ],height=(int)[ 16, 4096 ],framerate=(fraction)[ 0/1, 2147483647/1 ]
> 
> [omxjpegenc]
> type-name=GstOMXJPEGEnc
> core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
> component-name=OMX.realtek.image.enc
> rank=258
> in-port-index=0
> out-port-index=1
> sink-template-caps=video/x-raw,format=(string) { NV12 },width=(int)[16, 4096],height=(int)[16, 4096],framerate=(fraction)[ 0/1, 2147483647/1 ]
> src-template-caps=image/jpeg,width=(int)[ 16, 4096 ],height=(int)[ 16, 4096]
>

**Comment by darknebular** [comment]
Now here There is a decoder for 265:
**[omxh265dec]**
type-name=GstOMXH265Dec
core-name=/var/packages/CodecPack/target/lib/realtek/libOMX_Core.so
component-name=OMX.realtek.video.dec
rank=258
in-port-index=0
out-port-index=1
sink-template-caps=video/x-h265

Ummm interesting...

**Comment by Natzunur** [comment]
I have done some video testing, and think the problem is not for the h265 codec, but really audio codec.
- h264 movies with AAC/EAC3 audio is not working
- h265 every movies are not working (but they all are with AAC or EAC3 audio)
- mpeg4 + AC3 : not working
- mpeg4 + mp3 : not working (working before the wrapper ?)
-

**Comment by darknebular** [comment]
Yeah! the problem is with GSStreamer. 
Please send me this:
`/var/packages/VideoStation/target/bin/gst-launch-1.0 --version`

and I would try to enable H265 codec in VideoStation using the conf from CodecPack.

I would do this to try:
`mv /var/packages/VideoStation/target/etc/gstomx.conf /var/packages/VideoStation/target/etc/gstomx.conf.orig`
`cp /var/packages/CodecPack/target/pack/etc/gstomx.conf /var/packages/VideoStation/target/etc/gstomx.conf`

Regards.

**Comment by Natzunur** [comment]
adminjb@synojb:/$ /var/packages/VideoStation/target/bin/gst-launch-1.0 --version
/var/packages/VideoStation/target/bin/gst-launch-1.0: error while loading shared libraries: libgstreamer-1.0.so.0: cannot open shared object file: No such file or directory

I run your last commands to test the result ?

**Comment by darknebular** [comment]
Yes, you can revert the last 3 commands in case that something go wrong, because the first backup the original gstomx.conf to .orig.


Regards.

**Comment by Natzunur** [comment]
OK, I ran the 3 commands, but the video playback does not work (infinite loop)

Nothing in the "wrapper_ffmpeg.log"

**Comment by darknebular** [comment]
Hi, I am working in the wrapper for GSstreamer right now, I need this commands from DS218 play:

`cat /proc/cpuinfo`

`ls -la /var/packages/CodecPack/target/pack/lib`

`ls -la /var/packages/CodecPack/target/pack/bin`

`ls /var/packages/VideoStation/etc/gstreamer-1.0`

`ls -la /var/packages/CodecPack/etc/gstreamer-1.0`

`ls -la /var/packages/VideoStation/target/lib`


Thanks in advance

**Comment by darknebular** [comment]
Please, I added a GStreamer Wrapper for Play Devices like yours.

Could you uninstall the wrapper and then try to re-install, the installer SCPT_3.6 must detect your system and apply this GStreamer Wrapper.


Best Regards.

**Comment by Natzunur** [comment]
Hello !

I'have removed Wrapper/FFMEG/AME/VideoStation and reinstall all but still infinite loop :(
![Capture d’écran 2023-05-25 211442](https://github.com/darknebular/Wrapper_VideoStation/assets/133401347/8d9174bd-dbea-4d51-8cb7-0f126c5f79aa)

With your commands : 
![Capture d’écran 2023-05-25 211442](https://github.com/darknebular/Wrapper_VideoStation/assets/133401347/3799ecf6-096f-4f34-bfc8-d9a3d6a435c6)
[commands.txt](https://github.com/darknebular/Wrapper_VideoStation/files/11568513/commands.txt)


Thanks

**Comment by darknebular** [comment]
Ohhhh!!!!!!!
Sorry my friend.

I will work further in this.

Could you send me this?

`cat /tmp/wrapper_ffmpeg.log`


Regards.

**Comment by darknebular** [comment]
I have a clue, I think that It's the códecs caché of the gstreamer, due to This the plugins aren't loaded.

I think that This file Will be recreated at startup.

Could you delete This or move It if you don't want no delete It.

For delete de caché:
`rm -rf /var/packages/CodecPack/etc/gstreamer-1.0/registry.aarch64.bin`

For move the caché file another Path:
`mv /var/packages/CodecPack/etc/gstreamer-1.0/registry.aarch64.bin /tmp/`

Could you confirm This ?

Thanks in Advance.

**Comment by darknebular** [comment]
Look, It looks like that It's the problem that I am having:

https://forums.developer.nvidia.com/t/gstreamer-plugins-loading-issues/68253

**Comment by Natzunur** [comment]
Huge thanks once again for your time !

cat /tmp/wrapper_ffmpeg.log
=> Nothing but the installation of the wrapper

Done this :   rm -rf /var/packages/CodecPack/etc/gstreamer-1.0/registry.aarch64.bin

But still the same (infinite loop), also every video are not working now (no matter the audio/video codec)
=> Still nothing in the wrapper log

Please, I don't want to waste your time for my problem anymore, tell me if your are out of idea and we will rest here

**Comment by darknebular** [comment]
@Natzunur Yes, I am totally out of idea with this. I don't know very well GStreamer, I know FFmpeg. 
@hjh142857 I really aprecciate this, but I can't promise anything because I don't know gstreamer well. I'll try my best, but I'm alone in this project, out of time and it may take a while to find a fix. I think you can give me remote access to that NAS and thus avoid sending it to me, it gives me respect to have the responsibility of taking care of hardware that is not mine.

**Comment by th0ma7** [comment]
I do have an experimental synocommunity gstreamer package in the work.  Something we could chat over discord.

**Comment by darknebular** [comment]
I haven't discord, have you got other bias?. This guy confirm me that all formats are working fine now in DS-218-Play in local:
https://github.com/darknebular/Wrapper_VideoStation/issues/23

Good news!!

**Comment by rocky7x** [comment]
Hi, 

The same doesn't work on DS220j. Can you please also include DS220j in the same fix?

Thanks a lot.

**Comment by Natzunur** [comment]
I have try to remove everything and just resintall AME + VideoStation, even a simple video in mp4+mp3 (576 x 432) is not working...
And as on ds218 everything seems to work (https://github.com/darknebular/Wrapper_VideoStation/issues/23) , I think there is a problem with my synology caused by my multiple attemps / tests / hacks but i don't know how to find the root cause

**Comment by darknebular** [comment]
@hjh142857 Hi, the transcoding of AAC Will be not possible. Synology ends It's support for This códec.

Regards

**Comment by rocky7x** [comment]
Is there a possibility to play HEVC (h265) with normally supported sound codec via Video Station? Since when I play it in Firefox in Video Station, it says that the video codec is not supported.

**Comment by darknebular** [comment]
Using the Simplest not, with the Advanced Wrapper YES, you can play HEVC movies using any Browser because It's changing to h264.

Best Regards.

**Comment by rocky7x** [comment]
Hi,

Indeed I tried and it doesn't work, even with Advanced Wrapper - says that Video format is not supported by My Computer. The device is DS 220j. But why doesn't it work, when the AME package should enable the playing of HEVC? Or is it device-specific?

**Comment by darknebular** [comment]
It's device specific. In your system when the movie has got HEVC, It doesn't touch at all my Wrapper and use other binaries, these other binaries hasn't got any possibility to transcode DTS, EAC3 or TrueHD, and don't send to my Wrapper. Then due to this, This is not working in your system. It isn't related to a missconfiguration of my Wrapper.

Regards.

**Comment by darknebular** [comment]
In the Play devices is working because, its system send these kind of audio's codecs to decode via FFmpeg and then It uses my Wrapper.

**Comment by darknebular** [comment]
@hjh142857 Now It plays HEVC, I am investigating more:
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/b068a053-22cd-47c8-91f6-b56ec5741d66)

**Comment by darknebular** [comment]
@hjh142857  H264 +AAC is playing fine:
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/a14823bd-a988-4bf7-8033-79355033f7db)

**Comment by darknebular** [comment]
@hjh142857 Now The HEVC+AAC is working fine in DS218, I will publish the new version with these corrections:

![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/768c2dbe-c7c0-4bc0-8849-d721d6c1fe08)

**Comment by darknebular** [comment]
I just upload the new version with additionals libraries for GStreamer SCPT_3.9. 
**Now with AAC support for those devices without AAC support.**

Best regards.

**Comment by Natzunur** [comment]
Still not working here, but I think my VideoStation is broken... I will erase / reinstall DSM and try again in a few weeks

**Comment by darknebular** [comment]
@Natzunur

**Comment by darknebular** [comment]
Perhaps the DS120J has a software block and the DS218 not. I don't know. Synology does this kind of configurations in J devices and not in normal or Plus appliances, because J models are the Low-Entry, Low-performance and Low-Cost models...
But if your system doesn't touch the AME's binary, then It doesn't use my Wrapper at all. I can't do more.

Regards.
