### ISSUE TITLE
ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.

### ISSUE THREAD

**Issue by yanglinfei0760** [darknebular/Wrapper_VideoStation#27]
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/76809460/98317cbd-fd35-49eb-8137-eeb31abff06f)
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/76809460/49b02cbd-0998-41de-88d1-03df2695152c)

**Comment by darknebular** [comment]
It's loaded and installed the license, but NOT ACTIVATED.
Please try to transcoding something in order to activate it.

Best regards.

**Comment by HFfay** [comment]
同样的错误，然后去安装 AME license，但还是会报错。

难度是因为安装的SA6400 ，SN无效导致的？

![image](https://github.com/darknebular/Wrapper_VideoStation/assets/7297472/30a50dec-2df7-4d1d-927c-c4dba7e4a9e9)

**Comment by darknebular** [comment]
NOOO, You don't need the CRACK for AME.

You only need to activate the license, only you need to try a transcoding something in Video Station for example and just it.

**If you see a False doing this command, then It's NOT ACTIVATED:**

`cat /usr/syno/etc/codec/activation.conf`


Regards.
