### ISSUE TITLE
更新问题。

### ISSUE THREAD

**Issue by qunsi** [darknebular/Wrapper_VideoStation#28]
比方说，我自己写入的是3.3版本，你现在更新到3.9版本了，我需要重新写入吗？主要您更新比较频繁

**Comment by darknebular** [comment]
No va a haber nuevas actualizaciones en el instalador.
Hice cambios en el Wrapper en la 3.6 y el resto de cambios hasta 3.9 son sólo a la hora de instalar.

Voy a dejar la 3.9 como TLS, si quieres instala de nuevo. No voy a hacer más cambios.
Perdona las molestias.
