### ISSUE TITLE
Problem with DS923+

### ISSUE THREAD

**Issue by SoZee** [darknebular/Wrapper_VideoStation#31]
Hello dude,

Thank your for your wrapper.
I have migrate my NAS from RS815+ to DS923+ and now if i run your script i have this error : 

[2023-07-13 21:55:35] ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.

I have try to restart, and reinstall package AME but it don't work.

Do you have an idea for me ? 

Thank you.

**Comment by darknebular** [comment]
Hello, you are welcome.

Please, could you check This?

https://github.com/darknebular/Wrapper_VideoStation/issues/29#issuecomment-1603927930

**Comment by SoZee** [comment]
Hello

It's ok now ! 👍
Sorry for the inconvenance. 

And thank you again, for your good wrapper 👌😉

Bye

**Comment by darknebular** [comment]
Perfect, I Will close This ticket.

BEST regards.
