### ISSUE TITLE
VideoStation stopped getting information from https://www.themoviedb.org

### ISSUE THREAD

**Issue by spazCR** [darknebular/Wrapper_VideoStation#33]
After install the wrapper on my ds920+, video station stopped getting the movie metadata from the movie database.
The apikey is OK.

**Comment by darknebular** [comment]
Hello, getting information from tmdb doesn't touch my wrapper, It's only Video Station binaries.

**Comment by darknebular** [comment]
https://www.synoforum.com/threads/video-station-tmdb-api-key-problem.6577/
