### ISSUE TITLE
 ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.

### ISSUE THREAD

**Issue by teslaweiler** [darknebular/Wrapper_VideoStation#36]
ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.
![Screenshot from 2023-08-26 14-50-24](https://github.com/darknebular/Wrapper_VideoStation/assets/68001202/3fb7b25f-7ebc-489d-9101-96bb28b5d30c)

**Comment by darknebular** [comment]
You only have installed the AME license.
You Will need to transcode something using Video Station in order to ACTIVATE It.

Then you will be able to install the Wrapper.

BEST regards.

**Comment by teslaweiler** [comment]
> 

Thank you very much for your assistance and explanation! I appreciate your help in guiding me through the process of activating the AME license and installing the Wrapper. Best regards!

**Comment by am** [comment]
I'm facing the same issue, but I'm unsure how can I transcode a video. All the video I have with HEVC codec also have AAC audio and I'm not able to play them. 

How can I make sure the license is loaded? Is there any video sample you can point me to ir order to trigger the transcoding? Thank you

**Comment by darknebular** [comment]
You can do a offline transcoding in Video Station.
WITH This you will activate your license.
