### ISSUE TITLE
unable to transcode from video station

### ISSUE THREAD

**Issue by jhanyung** [darknebular/Wrapper_VideoStation#38]
Hi DarkNebula!

Thank you for your contribution and work.
I have AME3.0 with a green tick of approval (HEVC enabled)

I ran your code, and was told to transcode a video from VideoStation.
Now, I can play native videos but I tried to lower quality from videos to force transcode - I have spinning loading icon for hours.

Do you know if there are any solutions to address this?

thank you for your help.;

**Comment by jhanyung** [comment]
After a little bit more digging, it seems that it's related to my DSM version, which is  7.2 64570 update 3.

I'm still getting an MD5 mismatch because of my version and I am unable to downgrade.

would you know the correct binhash to add to, to this list?

`#arrays
declare -A binhash_version_list=(
    ["cde88ed8fdb2bfeda8de52ef3adede87a72326ef"]="6.0-7321-0_6.0.3-8754-8"
    ["ec0c3f5bbb857fa84f5d1153545d30d7b408520b"]="6.1-15047-0_6.1.1-15101-4"
    ["1473d6ad6ff6e5b8419c6b0bc41006b72fd777dd"]="6.1.2-15132-0_6.1.3-15152-8"
    ["26e42e43b393811c176dac651efc5d61e4569305"]="6.1.4-15217-0_6.2-23739-2"
    ["1d01ee38211f21c67a4311f90315568b3fa530e6"]="6.2.1-23824-0_6.2.4-25556-6"
    ["c2f07f4cebf0bfb63e3ca38f811fd5b6112a797e"]="7.0.1-42216-0_7.0.1-42218-5"
    ["796ac7fab2dcad7978a0e8ae48abc9150aba916c"]="7.1-42550-0_7.1-42661-4"
    ["22445f5b0d8b6714954b50930c47b8805cf32b98"]="7.1-42550-0_7.1-42661-4"
    ["18461b62813166652fd64a96e06237fde81925f7"]="7.1.1-42962-0_7.1.1-42962-4"
    ["d316d5b2b080346b4bc197ad5ad7994ac043a15d"]="7.2-64570-1_7.2-64570-1"
)

declare -A patchhash_binhash_list=(
    ["e5c1a65b3967968560476fcda5071fd37db40223"]="cde88ed8fdb2bfeda8de52ef3adede87a72326ef"
    ["d58f5b33ff2b6f2141036837ddf15dd5188384c6"]="ec0c3f5bbb857fa84f5d1153545d30d7b408520b"
    ["56ca9adaf117e8aae9a3a2e29bbcebf0d8903a99"]="1473d6ad6ff6e5b8419c6b0bc41006b72fd777dd"
    ["511dec657daa60b0f11da20295e2c665ba2c749c"]="26e42e43b393811c176dac651efc5d61e4569305"
    ["93067026c251b100e27805a8b4b9d8f0ae8e291c"]="1d01ee38211f21c67a4311f90315568b3fa530e6"
    ["873749b00e1624df4b01335e0b69102acc185eb9"]="c2f07f4cebf0bfb63e3ca38f811fd5b6112a797e"
    ["06d543b2aab5ea73600ca96497febdad96dc7864"]="796ac7fab2dcad7978a0e8ae48abc9150aba916c"
    ["3a5ed18dc41ff243f3481b6e3cf4770651df0b54"]="22445f5b0d8b6714954b50930c47b8805cf32b98"
    ["4bfa2a72da607752435e432545f98f1a0b3815a8"]="18461b62813166652fd64a96e06237fde81925f7"
    ["5b712ae3373bf4c1475743d42b28dd68c49d0946"]="d316d5b2b080346b4bc197ad5ad7994ac043a15d"
)

declare -A binhash_patch_list=(
    ["cde88ed8fdb2bfeda8de52ef3adede87a72326ef"]="00002dc0: 27000084c0eb4cb9b6000000badd6940\n00003660: 24f0000000e8961e000084c00f84b400"
    ["ec0c3f5bbb857fa84f5d1153545d30d7b408520b"]="00002dc0: 27000084c0eb4cb9b7000000bafd6940\n000036f0: 0000e8291e000084c0eb1eb9ec000000"
    ["1473d6ad6ff6e5b8419c6b0bc41006b72fd777dd"]="00002dc0: 27000084c0eb4cb9b7000000baad6a40\n000036f0: 0000e8291e000084c0eb1eb9ec000000"
    ["26e42e43b393811c176dac651efc5d61e4569305"]="00002dc0: 27000084c0eb4cb9ba000000badf6a40\n00003710: f0000000e8271e000084c0eb1eb9ef00"
    ["1d01ee38211f21c67a4311f90315568b3fa530e6"]="00002dc0: 27000084c0eb4cb9bd000000baf76a40\n00003720: 24f0000000e8261e000084c0eb1eb9f2"
    ["c2f07f4cebf0bfb63e3ca38f811fd5b6112a797e"]="00002dc0: 000084c0eb2141b8c1000000b9586c40\n00003780: 1d000084c0e90d0100009041b8f60000"
    ["796ac7fab2dcad7978a0e8ae48abc9150aba916c"]="000035b0: 74cd4889efe8f623000084c0eb004c8d\n000040a0: fdffff4c89efe80519000084c0eb0048"
    ["22445f5b0d8b6714954b50930c47b8805cf32b98"]="00003850: e7e89a27000084c0eb00488dac249000\n00004340: fdffff4c89efe8a51c000084c0eb0048"
    ["18461b62813166652fd64a96e06237fde81925f7"]="000038e0: e7e89a27000084c0eb00488dac249000\n000043d0: fdffff4c89efe8a51c000084c0eb0048"
    ["d316d5b2b080346b4bc197ad5ad7994ac043a15d"]="00004224: e87722000084c09090909090904c8dbd\n00004390: ffe80a21000084c0909090909090488b"`

**Comment by jhanyung** [comment]
Hi, I found out that MD5 is still the same in update 3. I just needed to follow:

https://xpenology.com/forum/topic/60005-advanced-media-extension-will-not-activate-dsm71-42661/page/7/

this page for help.
Now your script is working perfectly!! 

Thank you, closing the issue.

**Comment by darknebular** [comment]
> I have spinning loading icon for hours.

Hello, one thing is the Wrapper itself and another thing is the AME License's patch. The AME license's patch is optional and It's not mandatory in order to use the Wrapper.
The Wrapper will be able to play DTS, AAC, EAC3 and TRUEHD movies in VideoStation and Media Server.

The Advanced Wrapper will do two audio streams, one of them in 5.1. The Simplest, doesn't touch any VideoStation's arguments and will have only 2.0 when the movie needs to be transcoded.

You don't need to wait to finish the offline transcoding, only launch it in order to activate the license loaded.

Regards.

**Comment by darknebular** [comment]
If my wrapper works for you, could you give me a Star in my repository?
