### ISSUE TITLE
220j 无效

### ISSUE THREAD

**Issue by huyuanjun976** [darknebular/Wrapper_VideoStation#39]
220j   7.2的系统  多次安装均无法播放mkv

**Comment by darknebular** [comment]
¿Qué codecs tiene ese MKV?

**Comment by huyuanjun976** [comment]
视频
标题: 1080p HEVC SDR
编码: HEVC
配置: Main
等级: 120
分辨率: 1920x1080
长宽比: 16:9
隔行扫描: No
帧率: 25
比特率: 4045 kbps
位深度: 8 bit
动态范围: SDR
Video range type: SDR
像素格式: yuv420p
参考帧: 1


音频
标题: Cantonese - Chi - AAC - Stereo - Default
语言: chi
编码: AAC
配置: LC
布局: stereo
声道: 2 ch
比特率: 128 kbps
采样率: 48000 Hz
默认: Yes
强制: No
外部: No

**Comment by darknebular** [comment]
EL wrapper Simplest no funciona con este contenido porque VideoStation envía mal los argumentos y el Wrapper Simplest no modifica esos argumentos. Has probado a usar el Wrapper Avanzado?

**Comment by darknebular** [comment]
There isn't any feedback from the user.
