### ISSUE TITLE
DSM 7.0 Just run the script under "For DSM 7.0:" in README.md? 

### ISSUE THREAD

**Issue by juneszh** [darknebular/Wrapper_VideoStation#4]
Hello, my NAS is DS920+ and DSM version is 7.0.1-42218 Update 2

So I just run the script under "[For DSM 7.0:](https://github.com/darknebular/Wrapper_VideoStation#for-dsm-70)" in README.md?

**Comment by darknebular** [comment]
Yes, only this steps under DSM7.0.

**Comment by darknebular** [comment]
Issue Closed
