### ISSUE TITLE
Media Server not working (I suppose)

### ISSUE THREAD

**Issue by Laserchrist** [darknebular/Wrapper_VideoStation#40]
I installed the advanced wrapper but the Media Server doesn't work despite giving me the message that the installation was successful

I am trying to play video (with DTS) on TV:
- casting with DLNA to the TV, starting from VideoStation on PC, the video starts but there is no audio and I get a message on TV: "The Audio data is not supported"
- if I use the VideoStation app on the Samsung TV, the video starts but there is no audio, no message or warning is displayed (as far as I see from other issues submitted the TV app is not updated frequently or at all)
- if I browse the content of the NAS from the TV, **EVERY** video (DTS or not) fails to play and I have a network error (this never happened before patching)

please help

**Comment by darknebular** [comment]
Check it out these configs in Media Server:
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/e2ed6123-1a4a-4250-95ee-444a1ecf7454)
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/423c43b8-6225-4d56-a719-12291c9a492d)
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/cb6bfb68-c32a-4cbb-baf7-29b0b6a09d46)


Regards.

**Comment by Laserchrist** [comment]
I just tried and it is still not working, I get pretty much the same result

**Comment by darknebular** [comment]
Can you send me the log of the Wrapper?
The log is in /tmp/wrapper_ffmpeg.log and you can see it putting this:

`cat /tmp/wrapper_ffmpeg.log`

Regards.

**Comment by Laserchrist** [comment]
here the log, thank you for your patience
[wrapper_ffmpeg log.txt](https://github.com/darknebular/Wrapper_VideoStation/files/13284746/wrapper_ffmpeg.log.txt)

**Comment by darknebular** [comment]
I don't see any error there, Your TV probably doesn't support 5.1 AAC. Have you tried changing the first audio stream that the Wrapper sends to the TV using DLNA?

It is done in the menu, in the Wrapper configuration option, change it from AAC to AC3 5.1 in the audio sent by MediaServer.

**Comment by Laserchrist** [comment]
> I don't see any error there, Your TV probably doesn't support 5.1 AAC. Have you tried changing the first audio stream that the Wrapper sends to the TV using DLNA?
> 
> It is done in the menu, in the Wrapper configuration option, change it from AAC to AC3 5.1 in the audio sent by MediaServer.

Do you mean option C in config? I did, but I give it a try again now

**Comment by Laserchrist** [comment]
Hold on, things get a little weirder now:
Now some DTS are working, but some are not
Here is another log:
[Uploading wrapper_ffmpeg log2.txt…]()

**Comment by darknebular** [comment]
I can't see the log file.

Regards.

**Comment by Laserchrist** [comment]
> I can't see the log file.
> 
> Regards.

sorry, something went wrong, now should work
[wrapper_ffmpeg log2.txt](https://github.com/darknebular/Wrapper_VideoStation/files/13311518/wrapper_ffmpeg.log2.txt)

**Comment by darknebular** [comment]
I don't see any errors in the Wrapper's logs, I see that you have changed from AAC to AC3 and you have also changed the order, leaving the first audio as MP3 2.0.

What TV do you have exactly? I think it may be some peculiarity of your TV.


All the best.

**Comment by Laserchrist** [comment]
> I don't see any errors in the Wrapper's logs, I see that you have changed from AAC to AC3 and you have also changed the order, leaving the first audio as MP3 2.0.
> 
> What TV do you have exactly? I think it may be some peculiarity of your TV.
> 
> All the best.

Ok, I didn't change the order, just apply the C option, I'll try to set it again
The TV is Samsung S95BA: https://www.samsung.com/ie/tvs/oled-tv/s95b-65-inch-oled-4k-smart-tv-qe65s95batxxu/

**Comment by darknebular** [comment]
I think your TV doesn't know how to work with two audio streams of the same track. You could go into the Advanced Wrapper configuration and set it to only use one audio stream in Media Server or try the Simplest Wrapper that only sends one.

**Comment by Laserchrist** [comment]
I tried both and unfortunately, nothing worked, I am running out of ideas, I am trying all the profiles in DLNA media server

**Comment by darknebular** [comment]
How are you connect the TV with the NAS? via Ethernet or via Wi-Fi?

**Comment by Goitia** [comment]
I have the same issue with a Samsung S95C: https://www.samsung.com/es/tvs/oled-tv/s95c-65-inch-oled-4k-smart-tv-tq65s95catxxc
I try also al recomendation but not working.

All devices are conected via ethernet.

**Comment by darknebular** [comment]
casting with DLNA to the TV, starting from VideoStation on PC, the video starts but there is no audio and I get a message on TV: "The Audio data is not supported". **Please doesn't use VideoStation for launch DLNA.**
if I use the VideoStation app on the Samsung TV, the video starts but there is no audio, no message or warning is displayed (as far as I see from other issues submitted the TV app is not updated frequently or at all). **Yes, this App's version from Samsung Store is deprecated nowadays.**
if I browse the content of the NAS from the TV, EVERY video (DTS or not) fails to play and I have a network error (this never happened before patching). **If you have a network error using the plain DLNA Cliente, then your problem is with your networking configuration. Check it out the MTU, IP's, masks, gateways, in both edges (your NAS and your TV).**


I can see any error in the log from my Wrapper.

Regards.

**Comment by Goitia** [comment]
I only use the plain DLNA client in the TV. I can see all files exceptDTS, TRUEHD and EAC3 files.

Regards.

**Comment by darknebular** [comment]
> I only use the plain DLNA client in the TV. I can see all files exceptDTS, TRUEHD and EAC3 files.
> 
> Regards.

Has probado esta configuración?
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/d314a82b-1602-46bf-bcc3-bf5353bdcf20)

**Comment by Goitia** [comment]
Tengo la configuración exactamente así.

![image](https://github.com/darknebular/Wrapper_VideoStation/assets/1764736/af27baf9-59f0-4e10-9179-e32279a13418)

**Comment by darknebular** [comment]
Si quitas la opción de Habilitar transcodificación de Video, el DLNA del Media Server lo envía en nativo a la TV. Ahí no aplica el Wrapper, podemos ver si es un problema de incompatibilidad entre el DLNA de la TV y el del Media Server o de red local, etc.

**Comment by Goitia** [comment]
Si lo quito la opción. Muestra un mensaje de que el formato de audio no es compatible pero si se ve la imagen.

**Comment by Laserchrist** [comment]
> How are you connect the TV with the NAS? via Ethernet or via Wi-Fi?

I am on wifi
About playing content from the TV file browser: it used to work before patching with wrapper (no DTS obviously) now some files with DTS take very long but the TV opens it, some other just gives a "connection issue, try troubleshooting" message after a very long waiting.

**Comment by Laserchrist** [comment]
> casting with DLNA to the TV, starting from VideoStation on PC, the video starts but there is no audio and I get a message on TV: "The Audio data is not supported". **Please doesn't use VideoStation for launch DLNA.** if I use the VideoStation app on the Samsung TV, the video starts but there is no audio, no message or warning is displayed (as far as I see from other issues submitted the TV app is not updated frequently or at all). **Yes, this App's version from Samsung Store is deprecated nowadays.** if I browse the content of the NAS from the TV, EVERY video (DTS or not) fails to play and I have a network error (this never happened before patching). **If you have a network error using the plain DLNA Client, then your problem is with your networking configuration. Check it out the MTU, IP's, masks, gateways, in both edges (your NAS and your TV).**
> 
> I can see any error in the log from my Wrapper.
> 
> Regards.
I checked the LAN settings when this started and nothing was wrong there, again, it use to work before patching with wrapper
I'll try to check everything again and with cable as well

**Comment by darknebular** [comment]
Have you got other Wrappers installed previously?

**Comment by Laserchrist** [comment]
Yes, it was detected on the first time I installed this one (and auto-removed by this one, as far as I understand)

**Comment by darknebular** [comment]
Other wrappers do some changes and become permanents, doing issues.

I recomend to you, unistall Media Server, AME (Advance Media Extension) and Video Station and try again.

**Comment by Laserchrist** [comment]
> Other wrappers on Internet do some changes that there aren't nessesary in my Wrapper and become permanents, doing issues.
> 
> I recomend to you, unistall Media Server, AME (Advance Media Extension) and Video Station and try again.

I did it, and things are getting frustrating:

I removed the Wrapper, Video Station, Media Server, AME, FFmpeg 4,5,6
the only thing I kept is the VideoStation Database

I installed Video Station, AME, Media Server and now Video Station fails to play HDR 10 video properly (washed out output)

Help, please :(

**Comment by Laserchrist** [comment]
Can it be ffmpeg? version 4.1.9 is still in the system despite the uninstall

**Comment by darknebular** [comment]
You need for my Wrapper the FFMEPG 6.x version

**Comment by darknebular** [comment]
Your problem is not with my Wrapper, I am using this Wrapper and all is working fine with a lot of TVs. You haven't any error in the Wrapper's logs.
I think that your problem is with your DLNA version between your NAS and your TV, network outages or problems, lack of bandwidth, etc.

**Comment by Laserchrist** [comment]
I see, I've reached Synology to fix my issue and then I will try again with your wrapper
