### ISSUE TITLE
Not working 216p bluray AV1 TrueHD5.1

### ISSUE THREAD

**Issue by KumanduS** [darknebular/Wrapper_VideoStation#42]
<img width="468" alt="Capturar1" src="https://github.com/darknebular/Wrapper_VideoStation/assets/105173673/a4148940-b47f-411c-815a-d196b1fa4dbb">

**Comment by darknebular** [comment]
Many CPUs do not support AV1 decoding, it does not depend on the capabilities of my Wrapper.
