### ISSUE TITLE
Typo in AME License Fix

### ISSUE THREAD

**Issue by fantopop** [darknebular/Wrapper_VideoStation#43]
When running AME License Crack the `installer_OffLine.sh` couldn't successfully patch the AME due to two white spaces in lines 808 and 811:

```
808: content= '[{"appType": 14, ...
811: content= '[{"appType": 14, ...
```

After removing these white spaces the script worked like a charm!

**Comment by darknebular** [comment]
Thank you so much.

Please feel free to create a pull request so you can appear in the credits as a thank you.

All the best.

**Comment by darknebular** [comment]
I'm not sure which two blank spaces you mean, the ones at the beginning of the line?

**Comment by darknebular** [comment]
I can't see which two spaces you are referring to. Sorry, I'm going to close the case, if you want to help me please be more specific, the license patch works perfectly for me without deleting anything.


Regards, and thank you very much.

**Comment by darknebular** [comment]
**THANKS!!!!**
