### ISSUE TITLE
AME licence error

### ISSUE THREAD

**Issue by SayonaRRRa** [darknebular/Wrapper_VideoStation#44]
Hi there and congratulations on keeping your wrapper in the works.
It seems I keep running into this error when I try to run your patch on a fresh baremetal install
Loader RR v23.11.6
DSM 7.2.1-69057 Update 3
I get this:

```
Please, What option wish to use?i
You have ALL necessary packages Installed, GOOD.
[2023-12-20 12:34:55] ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.
root@KAO-CLOUD:/volume1/video#
```
Although I have it patched and it shows as activated:
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/33625430/d44eac04-1a7e-46ec-9787-cd98c0ce6baf)

Any thoughts for using your wrapper and not Alex' Presso 's one ?

**Comment by SayonaRRRa** [comment]
Forgot to mention , AME was patched with `ame72-3005.py`

**Comment by darknebular** [comment]
You need to activate your License. You only have installed the license but you need to activate the license.

In order to activate the license you need to transcode something in Video Station.

If you use my Wrapper you will be able to configure the codecs order, have 5.1 in the transcoding and you will have the DLNA Media Server patched too at once.


Best regards.

**Comment by SayonaRRRa** [comment]
I perfectly understand your point, but why when I apply Ales Presso's patch , everything streams and plays without having anything played before. It just works.

**Comment by darknebular** [comment]
Because his script is patching a not ideal path and He doesn't need to check it out the AME license.

**Comment by SayonaRRRa** [comment]
For instance if I have not yet activated the AME license ( activated in this case actually means it asks me to login to syn account ) I cannot stream HEVC content or view with with Video Station. I activate it with an offline patch, apply Alex's codec patch and streaming begins like it should in Video Station and or mobile or chromecast etc. 
I understand you make this available for free but it just doesn't work for me. 
I wish I would have a piece of video to stream and "activate" the AME like you said, but I'm afraid there's a language barrier there or your method is incomplete for the purposes people like us who make baremetal builds try to use your type of wrapper.
I could make a video showing what I mean and share it with you if you like. The steps I take etc...
In case you built your wrapper exclusively for original hardware then maybe I'm asking too much .
I would really love to use and to support your work , but jumping through complicated hoops is something people might not have time for.
Can your script include "activation" or what you think that means for AME prior to applying the codec patch ? Just asking, wouldn't it be easier this way ?
Thank you so much for taking the time to reply here.

**Comment by SayonaRRRa** [comment]
Update...I downloaded a Tom&Jerry Colletion ( this build is for someone with kids ) It was a low bit rate, mp3 audio Xvid file. Managed to view it in VideoStation. I ssh-ed into the NAS and was able to run your patch with no issues this time. And was able to stream a 4K HEVC file after the patch, so for now it looks like its working.
I will try the streaming mobile apps and chromecast too and will comeback with an update.

**Comment by darknebular** [comment]
I did this because I patch the AME folder and not the VideoStation folder (like Alex's does). The full path to the AME folder is not generated until the license is activated, that is why I need that folder to be generated and that is why I need to verify that the license is installed and activated.
