### ISSUE TITLE
HEVC files not playing

### ISSUE THREAD

**Issue by fildar** [darknebular/Wrapper_VideoStation#47]
Hello,

First of all, I would like to thank you for all your work (and Benjamin's before you) because I have been using the wrappers since ages and my family and friends are thankful :)

For the tests, I use Video Station in Chrome last version.
My only issue seems to be with HEVC files... (according to the logs attached)
[HEVC+AAC_NOK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146764/HEVC%2BAAC_NOK.txt)
[HEVC+AC3_NOK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146765/HEVC%2BAC3_NOK.txt)
[HEVC+DTS_NOK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146766/HEVC%2BDTS_NOK.txt)
[HEVC+EAC3_NOK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146767/HEVC%2BEAC3_NOK.txt)
[H264+AAC_OK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146768/H264%2BAAC_OK.txt)
[H264+AC3_OK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146769/H264%2BAC3_OK.txt)
[H264+DTS_OK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146770/H264%2BDTS_OK.txt)
[H264+EAC3_OK.txt](https://github.com/darknebular/Wrapper_VideoStation/files/14146771/H264%2BEAC3_OK.txt)

If I am not mistaken, there is no error in the wrapper log files.

Steps followed :
1. Uninstall the wrapper :  _`bash -c "$(curl "https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/installer.sh")" -- -s uninstall`_
2. Uninstall AME
3. Uninstall Video Station (but keep the DB)
4. Uninstall FFMPEG 6 and erase all files
5. Install AME (Codecs pack still appears install after...)
6. Install FFMPEG 6
7. Install Video Station
8. Install the wrapper : _`bash -c "$(curl "https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/installer.sh")" -- -s install`_

I am sure AME is install and activated but I don't know how to test and resolve this...

![image](https://github.com/darknebular/Wrapper_VideoStation/assets/16326923/3cd82f09-3db5-42f4-be4e-f040d4b3a96e)

Any idea ?

**Comment by darknebular** [comment]
Please, look this:
https://caniuse.com/hevc

As you can see there, HEVC is not supported in many browsers, to watch HEVC you must watch it using a chromecast or GoogleTV or cast them via DLNA to TVs.

I've tested HEVC under those conditions (including a web browser with HEVC support) and it worked fine.

**Comment by darknebular** [comment]
Unfortunately I can't fix this lack of HEVC support in the Chrome browser in my Wrapper.

I proceed to close the ticket and thank you for using my Wrapper and for the time you have had to write to me.

Greetings.
