### ISSUE TITLE
Wrapper Synology

### ISSUE THREAD

**Issue by BagutoSI** [darknebular/Wrapper_VideoStation#5]

**Comment by Giovanni0000** [comment]
Hi, script works fine, all videos with eac3 format are playable, i noticed CPU increase after wrapper install. Before it was arrount 10% on single video play on DS video, now its 50% usage playing eac3 files, 720p resolution is same, bitrate too. Any idea?

DSM 7.1.1-42962 Update 3
VIDEO STATION 3.0.5.-2503
ffmpeg 4.4.3-47
