### ISSUE TITLE
the wrapper work good at my PC video station , but don`t work at my mobile video station

### ISSUE THREAD

**Issue by GMenethil** [darknebular/Wrapper_VideoStation#51]
the wrapper work good at my PC video station , but don`t work at my mobile video station. My android video station and ios video station can't paly video , It keeps spinning when reading the video

**Comment by darknebular** [comment]
Please install MX PLAYER and check it out that you have all these configs like me:
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/75a821c1-4660-4635-a5ce-4bc0befab789)


Best Regards.
