### ISSUE TITLE
[QA] Restore AAC support for the Audio Station?

### ISSUE THREAD

**Issue by fghber** [darknebular/Wrapper_VideoStation#54]
Hi. This is a bit OT but would it be possible to restore AAC support for the Audio Station (DSM 6.2 and newer) similarly to the the Video Station patcher? I used to play my music directly to a USB speaker but it now only works with MP3 files which is rather disappointing.
I like to give it a try but have a hard time getting started. Thank you!

**Comment by darknebular** [comment]
Audio Station does not allow AAC codec, it does not send the files to the CodecPack, therefore my Wrapper will not be able to be activated or used. Maybe if you try activating this configuration in the options, you can force the CodecPack to use the FFMpeg, but as you see, AAC is not listed there...

![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/889dbdd4-d984-470c-9e0d-e99101457fd6)

My Wrapper is only valid for VideoStation.


I have no plans to make another Wrapper, I am proceeding to close the ticket. If you have questions or if the option I told you above finally worked for you, let me know.

Regards, and thank you very much.
