### ISSUE TITLE
Wrapper not work with multiple issues

### ISSUE THREAD

**Issue by lazydreamerbliss** [darknebular/Wrapper_VideoStation#56]
I am running DSM7.2.1 on 423+, ffmpeg community/AME/media server/video station all installed, wrapper version is Advanced Wrapper
- ffmpeg version: 6.0-2
- AME version: 1.1.0-01006
- video station version: 3.1.1-3168

Issue1:
- After the installation of wrapper, come previously-playable videos, and ALL DSM-not-supported ones (such as DTS) are unplayable with infinite pending
- This issue will be gone if I uninstall the wrapper, that the previously-playable videos will be playable again, while DSM-not-supported ones show up the unsupported message
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/8576808/36e6fb86-b49b-44bc-93c8-f189f2f68020)

Issue2:
- Tried to solve issue1 by config the Advanced wrapper, and the installer script notifies `Actually You HAVEN'T THE ADVANCED WRAPPER INSTALLED so this codec Configurator CAN'T change anything`, and if I choose to install (since it says I haven't installed the advanced wrapper) then I will get the message `Actually you have an OLD or OTHER patch applied in your system, please UNINSTALL OLDER Wrapper first.`
- I cannot resolve this one, tried to install/uninstall the Advanced Wrapper multiple times but all got no luck
- (There is not error during the installation)
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/8576808/8cf63ff9-da39-4fc8-905d-229001eea55e)

**Comment by darknebular** [comment]
Your problem seems to be because your system has another Wrapper installed from someone else. During the installation, (option I) of the main menu, if it detects that there is an old Wrapper or someone else's, if you click the YES option to delete the old Wrappers, try to leave the system as clean as possible before starting the installation of the Advanced wrapper.

**Comment by lazydreamerbliss** [comment]
Hi @darknebular , nope that is not the case, the second error is just a demo to prove that I have already got advanced wrapper installed

I didn't install any other wrappers except this one, and if I do the following the error will be always reproable:
1. Uninstall everything by option `u` (good)
2. Reinstall advance wrapper by option `i` (good)
3. Try to change the wrapper config by option `c` (error: Actually You HAVEN'T THE ADVANCED WRAPPER INSTALLED so this codec Configurator CAN'T change anything)
4. Try to install advance wrapper by option `i` again, without uninstall, because step3 says "I got no advance wrapper installed" (error:  Actually you have an OLD or OTHER patch applied in your system, please UNINSTALL OLDER Wrapper first.)

**Comment by lazydreamerbliss** [comment]
Oh I see the problem, my DSM cannot recognize `raw.githubusercontent.com`'s cert and failed to `wget` the injection file... Do you know how can I resolve this? I can wget the github but not raw.githubusercontent, strange really

**Comment by darknebular** [comment]
It is very strange, the certificate that shows me the raw subdomain. is valid, I don't know why your system doesn't trust it.

Try to put in ffmpeg41 the content of the file from my repository called: https://github.com/darknebular/Wrapper_VideoStation/blob/main/ffmpeg41-wrapper-DSM7_X-Advanced

**Comment by lazydreamerbliss** [comment]
Thanks @darknebular ! I replaced the wget with local file copy and it works
