### ISSUE TITLE
How do I check which version of FFMPEG VideoStation is using?

### ISSUE THREAD

**Issue by bgyooPtr** [darknebular/Wrapper_VideoStation#57]
I have FFMPEG versions 4 and 6 installed on my system.
The system default is version 4. (ffmpeg -v)
I want VideoStation to be wrapped with FFMPEG version 6.
How can I run the script (install.sh) and check whether VideoStation is using FFMPEG6?

**Comment by darknebular** [comment]
My Wrapper only works with FFMpeg version 6. 
Just uninstall other Wrappers and start my Wrapper's installer and everything will be done using version 6 in the Video Station's Wrapper.

Greetings.
