### ISSUE TITLE
( C ) Change the config of the Advanced Wrapper - will not detect wrapped installed 

### ISSUE THREAD

**Issue by KipiKland** [darknebular/Wrapper_VideoStation#6]
INFO: Actually You HAVEN'T ANY WRAPPER INSTALLED and this codec Configurator CAN'T change anything.

However wrapper look to be installed and HEVC/EAC3 movie playing fine on DS920+ as such i believe the wrapper does the job.

**Comment by darknebular** [comment]
It had been fixed in SCPT_1.11.

Best regards.

**Comment by darknebular** [comment]
It had been fixed in SCPT_1.11.

Best regards.
