### ISSUE TITLE
FFmpeg6.0.1-3

### ISSUE THREAD

**Issue by beleebala** [darknebular/Wrapper_VideoStation#60]
I note that the minimum version of FFmpeg required is 6.0.2. However, I the latest version I have from SynoCommunity is 6.0.1-3. Is there another source for getting the correct version of FFmpeg? Thanks.

**Comment by darknebular** [comment]
NO, My wrapper works with 6.0.1 also without problems. The stable version now is 6.0.1-3. 
When you update your FFMpeg, Video Station or AME package, you need to reinstall again the Wrapper.
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/4e345cca-4986-4ae1-8cb4-20224ceb4ae0)
