### ISSUE TITLE
Problems with a VideoStation's flag using DTS with ffmpeg7

### ISSUE THREAD

**Issue by Yod4z** [darknebular/Wrapper_VideoStation#65]
I have uninstall ffmpeg6 and install ffmpeg7
but move with DTS or EAC3 not working
I try to install the warpper but it can't use ffmpeg7
[2024-10-04 12:17:37] ERROR: MISSING ffmpeg6 Package.
At least you need 1 package/s to Install, please Install the dependencies and RE-RUN the Installer again.

**Solution before modification of the warrper** : install ffmpeg6

**Comment by th0ma7** [comment]
Hi @darknebular , fyi i updated all Synology ffmpeg to now uses a synocli-videodriver package that now supports opencl on dsm7 x64 archs (at least newer intel archs compatible with iHD driver as older using legacy i965 aren't compatible).

I also marked ffmpeg6 as no longer supported as there are no longer any package depending on it.  As such i don't intend to release any updates on that v6 branch.

**Comment by darknebular** [comment]
> I have uninstall ffmpeg6 and install ffmpeg7 but move with DTS or EAC3 not working I try to install the warpper but it can't use ffmpeg7 [2024-10-04 12:17:37] ERROR: MISSING ffmpeg6 Package. At least you need 1 package/s to Install, please Install the dependencies and RE-RUN the Installer again.
> 
> **Solution before modification of the warrper** : install ffmpeg6

Ok, I will change this to use the new version, because de version 6 is deprecated.

**Comment by darknebular** [comment]
Now the Script is only compatible with FFmpeg 7.X
### CHANGES:

****SCPT_3.9.9: Support for the new versions of FFMPEG 7.0.X and deprecate the use of ffmpeg 6.X.X. **

The version 6 is deprecated and removed from dependencies.

Could you install again and test with this new version of my script?

Regards.

**Comment by darknebular** [comment]
> Hi @darknebular , fyi i updated all Synology ffmpeg to now uses a synocli-videodriver package that now supports opencl on dsm7 x64 archs (at least newer intel archs compatible with iHD driver as older using legacy i965 aren't compatible).
> 
> I also marked ffmpeg6 as no longer supported as there are no longer any package depending on it. As such i don't intend to release any updates on that v6 branch.

Th0ma7, with this new version the DTS crash with DTS, look:
![image](https://github.com/user-attachments/assets/1432f4b0-a091-4cbd-aade-a7bb9ce697eb)

Do I need to change something in my Wrapper or is something missing in your binary?

Sincerely.

**Comment by darknebular** [comment]
vbsf, this flag has been deprecated from FFmpeg 7.0.
Video Station send to my Wrapper this flag when It's DTS codec.
I think that I will need to change this parameter in my Wrapper or you can add this legacy option to your binary?

I need a little help with the maintenance of my Wrapper, I'm short on time.

**Comment by th0ma7** [comment]
I certainly won't have time to port that over unless this is trivial...  If the argument simply changed name that's easy.  Otherwise i won't have the cycles dor that.

But note that while v6 is deprecated, it is still available in our repository so upgrading could wait for most people.

**Comment by darknebular** [comment]
**FIXED IN THE NEW VERSION SCPT_3.9.9**
