### ISSUE TITLE
when input ‘i’, have an error message below

### ISSUE THREAD

**Issue by Micah365** [darknebular/Wrapper_VideoStation#66]
ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.

![image](https://github.com/user-attachments/assets/7ae8db1f-f319-4723-98d5-8a27706e7ada)

DS918+   7.2.1-69057
AME 3.1.0-3005
HEVC 1.1.0-01006

![image](https://github.com/user-attachments/assets/71503fad-b23e-4504-9b8b-02426d778b0d)

**Comment by darknebular** [comment]
You need to transcode something in VideoStation for activate this license loaded.
The license must be LOADED and ACTIVATED.

Regards.
