### ISSUE TITLE
No "SynoCli Video Driver" in packet center

### ISSUE THREAD

**Issue by rugalcs** [darknebular/Wrapper_VideoStation#67]
Hello. First of all, thanks to all the community who makes possible this kind of features.
I have a DS116 Synology DiskStation, and I arrived here looking for the problem with AC3 audio.
I started following the steps and adding the SynoCommunity repository, but when I tried to search the "SynoCli Video Driver", I cannot find it on the Community folder. Here is an image of all the packages who appears in my search:

![synocommunity](https://github.com/user-attachments/assets/e55aa882-2004-47a4-8f09-d2b8fbf5d04b)

My DS116 has DSM 7.2.1-69057 Update 5, with an MARVELL Armada 385 88F6820 CPU.
Somebody can help me with the process? Thanks!

**Comment by darknebular** [comment]
According to the creator of the FFmpeg package, on devices that do not have Intel, it will not let you install it, in theory according to the creator of said package, it should let you install the FFmpeg package without needing the other package called CliVideo Driver.

**Comment by th0ma7** [comment]
I confirm, only intel based Synology nas requires it.  You should be able to install ffmpeg7 without it for your usecase.  If not please open up an issue on spksrc GitHub.
