### ISSUE TITLE
License in Advanced Media Extension not detected

### ISSUE THREAD

**Issue by Tofnet** [darknebular/Wrapper_VideoStation#7]
Hello,
During the installation I get the error:
`ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.`
Version of Advanced Media Extensions: 2.0.1-1021
Codecs pack: 1.0.0-00001
State: up to date
(Medias Server not installed, DSM 7.1-42661 Upd4)

I tried to uninstall and reinstall the AME package but while the update time is updated, the codec pack version remains the same as if it was the last one.

Edit: Same problem with DSM 7.1.1-42962 Update 1 and AME 3.0.1-2004 => Codecs pack: 1.0.0-00001 up to date

**Comment by darknebular** [comment]
You see this?

![image](https://user-images.githubusercontent.com/82757922/195530692-83f162df-8ad1-431b-8fa7-56b062df6691.png)

**Comment by darknebular** [comment]
If you have a "False" in /usr/syno/etc/codec/activation.conf Then You haven't a legit synology product.

Regards.

**Comment by Tofnet** [comment]
Hi darknebular, no I see this:
![image](https://user-images.githubusercontent.com/62984872/195580103-4f1a1542-6a06-4c94-a2c7-904ef3e5d870.png)

And the folder codec doesn't exist in etc... I tried:
 `find / -name activation.conf`
...without success.
Is there any way to reinstall the pack?
I don't know why I would be a special case.
Thank you for your help.

**Comment by Tofnet** [comment]
It works, you put me on the path:
With a quick google search I found this post on Reddit:

> ok it was because I had not yet started a trascode. I opened videostation and put on a video file. Then changed the video quality settings from original to lower - to force transcode. Now it works.

As a result, the codec folder appeared:
`{"success":true,"activated_codec":["mpeg4part2_dec","h264_dec","h264_enc","ac3_dec","hevc_dec"],"token":"`

But I am missing several codecs compared to you and I am still in version 00001. Any ideas?

BR

**Comment by Tofnet** [comment]
For the absence of the AAC codec, Synology gives reason: [Why can't I play AAC encoded files?](https://kb.synology.com/en-nz/DSM/tutorial/Why_cant_I_play_AAC_encoded_files)

I just quickly tested your wrapper, it seems to work well, even with my lower version. Thanks for the work!
