### ISSUE TITLE
DSM 7.1.1-42962 Update 1 video station can't generate video thumbnails

### ISSUE THREAD

**Issue by Sunwukong888** [darknebular/Wrapper_VideoStation#8]
hello, thanks for your great work
however I meet some problems. my dsm is 7.1.1-42962 Update 1 and my video station is 3.0.4-2107. when I use your solution, I find my video station can't generate video thumbnails which can generate random picture thumbnails before.
best wish for you!
![capture](https://user-images.githubusercontent.com/23336836/196045954-c9f2039a-4d6e-4aa3-a4b3-90b49e08850d.png)

**Comment by darknebular** [comment]
In my system and others is working fine:
![image](https://user-images.githubusercontent.com/82757922/196140510-e58a128e-0004-4c79-846d-958d9d305137.png)

Have you tried to uninstall Video Station and then reinstall it with a reinstallation of my wrapper?

Do you have any other wrapper o change in Video Station?

Can you send me the log in /tmp/wrapper_ffmpeg.log


Thanks.

**Comment by darknebular** [comment]
In the logs I can see that the thumbnails aren't using my wrapper, the problem looks like that It isn't due for my wrapper...
I will investigate this issue, but I think that the problem is other thing...

**Comment by darknebular** [comment]
I haven't this bug:
![image](https://user-images.githubusercontent.com/82757922/196672138-1f5c00fe-6769-4962-bccf-e72bcd0857c5.png)

it captures random picture in video as thumbnail perfectly.

**Comment by darknebular** [comment]
Can you confirm me if you have these options enabled?
![image](https://user-images.githubusercontent.com/82757922/196674522-85594052-cc2a-42b0-9bdd-17dda05dd048.png)

**Comment by darknebular** [comment]
Please confirm this config too:
![image](https://user-images.githubusercontent.com/82757922/196675052-dd980854-bc05-4efc-93af-5df1d0bae2b2.png)


It isn't problem of my wrapper.
